import Footer from "@/components/common/footer"
import Header from "@/components/common/header"
import Providers from "@/app/providers"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header></Header> 
            {children}
          <Footer></Footer>
        </Providers>
      </body>
    </html>
  )
}

